[build]
  command = "npm run build -- --configuration production"
  publish = "www"
  functions = "netlify/functions"

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/tmdb-proxy/:splat"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
